Compatibility for Classic and Burning Crusade Classic
Nevcairiel/Routes pull request #1
Opened 2021-06-16 19:59 UTC by EsreverWoW

These were my local changes for Classic and Burning Crusade Classic while maintaining compatibility with Mainline.

2021-06-16 20:09 UTC, Nevcairiel commented
Separate TOC files are not supported by the majority of tooling yet, please don't include them yet.

2021-06-16 20:14 UTC, Orphis commented on Routes.lua
> +		if Routes:isClassic() then
For BCC as well. Probably better in the current condition to have a "isMainline" and have the else handle all classic (and future) variants.

2021-06-16 20:16 UTC, Orphis commented on Modules/AutoShow.lua
> +	options.args.auto_group.args.archaeology = nil
You could just use GetSpellInfo() with proper spellIds to filter out professions that aren't in the game currently, then you don't have to check the expansion and you can make the code kind of generic.

2021-06-16 21:01 UTC, EsreverWoW commented on Modules/AutoShow.lua
> +	options.args.auto_group.args.archaeology = nil
Using GetSpellInfo() is an option, but it doesn't look as clean in my opinion. You wind up with something like this at a minimum.

```lua
local active_tracking = {}
local profession_to_skill = {}

profession_to_skill[GetSpellInfo(2575)] = "Mining"
profession_to_skill[GetSpellInfo(7620) or GetSpellInfo(131476)] = "Fishing"

if not Routes:isClassic then
	profession_to_skill[GetSpellInfo(9134)] = "Herbalism"
	profession_to_skill[GetSpellInfo(4036)] = "ExtractGas"
	if GetSpellInfo(78670) then
		profession_to_skill[GetSpellInfo(78670)] = "Archaeology"
	end
else
	profession_to_skill[GetSpellInfo(170691)] = "Herbalism"
end

local tracking_spells = {}

tracking_spells[(GetSpellInfo(2383))] = "Herbalism"
tracking_spells[(GetSpellInfo(2580))] = "Mining"
tracking_spells[(GetSpellInfo(2481))] = "Treasure"

if not Routes:isClassic() then
	tracking_spells[(GetSpellInfo(43308))] = "Fishing"
	if GetSpellInfo(167898) then
		tracking_spells[(GetSpellInfo(167898))] = "Logging"
	end
end
```

The last few lines could maybe be cleaned up a bit like so:
```lua
if not Routes:isMainline() then
	if not Routes:isBCC() then
		options.args.auto_group.args.gas = nil
	end
	options.args.auto_group.args.archaeology = nil
	options.args.auto_group.args.logging = nil
end
```

2021-06-16 21:09 UTC, EsreverWoW commented on Modules/AutoShow.lua
> +	options.args.auto_group.args.archaeology = nil
```lua
profession_to_skill[GetSpellInfo(Routes:isMainline() and 170691 or 9134)] = "Herbalism"
```
Another option for Herbalism maybe.

2021-06-16 21:20 UTC, Orphis commented on Modules/AutoShow.lua
> +	options.args.auto_group.args.archaeology = nil
My local version reads like this and doesn't use the profession_to_skill in classic code. Untested with classic at the moment, works with BCC though:
```lua
if WoWRetail then
	profession_to_skill[GetSpellInfo(2366) or GetSpellInfo(170691)] = "Herbalism"
	profession_to_skill[GetSpellInfo(2575)] = "Mining"
	profession_to_skill[GetSpellInfo(7620) or GetSpellInfo(131476)] = "Fishing"
	profession_to_skill[GetSpellInfo(4036)] = "ExtractGas"
	if GetSpellInfo(78670) then
		profession_to_skill[GetSpellInfo(78670)] = "Archaeology"
	end
end
local tracking_spells = {}
tracking_spells[(GetSpellInfo(2580))] = "Mining"
tracking_spells[(GetSpellInfo(2383))] = "Herbalism"
tracking_spells[(GetSpellInfo(43308))] = "Fishing"
tracking_spells[(GetSpellInfo(2481))] = "Treasure"
if GetSpellInfo(167898) then
	tracking_spells[(GetSpellInfo(167898))] = "Logging"
end

local classic_spell_ids = {
	Herbalism = { 2366, 2368, 3570, 11993, 28695 },
	Mining = { 2575, 2576, 3564, 10248, 29354 },
	Fishing = { 7620, 7731, 7732, 18248, 33095 },
	ExtractGas = { 30350 }, -- From Master Engineering
}

function AutoShow:SKILL_LINES_CHANGED()
	for k, v in pairs(have_prof) do
		have_prof[k] = false
	end
	if WoWRetail then
		for index, key in pairs({GetProfessions()}) do
			local name, icon, rank, maxrank, numspells, spelloffset, skillline = GetProfessionInfo(key)
			if profession_to_skill[name] then
				have_prof[profession_to_skill[name]] = true
			end
		end
	else
		for professionName, spellIds in pairs(classic_spell_ids) do
			for k, spellId in pairs(spellIds) do
				if IsPlayerSpell(spellId) then
					have_prof[professionName] = true
					break
				end
			end 
		end
	end
	self:ApplyVisibility()
end
```

And removing the entries from the options array, I add them at the end (or you could remove them inverting the check):
```lua
if GetSpellInfo(30427) then
	options.args.auto_group.args.gas = {
		name = L["ExtractGas"], type = "select",
		desc = L["Routes with Gas"],
		order = 200,
		values = prof_options3,
		arg = "ExtractGas",
	}
end

if GetSpellInfo(78670) then
	options.args.auto_group.args.archaeology = {
		name = L["Archaeology"], type = "select",
		desc = L["Routes with Archaeology"],
		order = 600,
		values = prof_options3,
		arg = "Archaeology",
	}
end

if GetSpellInfo(167898) then
	options.args.auto_group.args.logging = {
		name = L["Logging"], type = "select",
		desc = L["Routes with Timber"],
		order = 800,
		values = prof_options2,
		arg = "Logging",
	}
end
```

2021-06-16 21:58 UTC, EsreverWoW commented on Modules/AutoShow.lua
> +	options.args.auto_group.args.archaeology = nil
I think your approach is perhaps the more elegant one. Only thing that I noticed was that GetSpellInfo(43308) would return nil in Classic since it doesn't exist before Burning Crusade. It would need a conditional as well.
```lua
if GetSpellInfo(43308) then
	tracking_spells[(GetSpellInfo(43308))] = "Fishing"
end
```

2021-06-17 05:56 UTC, Nevcairiel requested changes

2021-06-17 05:56 UTC, Nevcairiel commented on Modules/AutoShow.lua
> +
This whole block would probably be cleaner by just using "hidden = not GetSpellInfo(xxx)" in the main options table, or is there any issues with the options existing?

2021-06-17 05:56 UTC, Nevcairiel commented on Modules/AutoShow.lua
> +	if Routes:isClassic() then
if not GetTrackingInfo then...

2021-06-17 05:56 UTC, Nevcairiel commented on Modules/AutoShow.lua
> +	if Routes:isMainline() then
if not GetProfessions then..

2021-06-17 05:56 UTC, Nevcairiel commented on Modules/AutoShow.lua
> +if Routes:isMainline() then
if GetProfessions then..

2021-06-17 05:56 UTC, Nevcairiel commented on Modules/AutoShow.lua
> +		if Routes:isClassic() then
if not GetTrackingInfo..

2021-06-17 05:56 UTC, Nevcairiel commented on Routes.lua
> +
With most checks above changed to checking the presence of API function that are required to run it, these should just go, and the last two places below have the check in-lined. (BCC is already unused before)

2021-06-17 07:06 UTC, EsreverWoW commented
I've gone ahead and made adjustments as you requested, Nevcairiel.

2021-06-17 07:06 UTC, Nevcairiel approved these changes

2021-06-17 09:24 UTC, Nevcairiel commented
Merged in 2ac985fe20e01eb5f65fb01f9e91f18584d3695c

2021-06-17 09:24 UTC, closed without merging